### ISSUE TITLE
Consider renaming this repository

### ISSUE THREAD

**Issue by aaronfranke** [joho/godotenv#113]
The first 5 letters of this repository spell "Godot", which is the name of a popular open source game engine. This means that the name of this repository can be confusing at first glance, and it shows up in searches for Godot.

Perhaps `go-dotenv` would be a good name. It separates `go` from `dotenv` while still being mostly the same name.

If you rename the repository, [the old link becomes a redirect and existing URLs and scripts will continue to work](https://docs.github.com/en/github/administering-a-repository/renaming-a-repository).

CC @joho

**Comment by DeadlySurgeon** [comment]
Go package names shouldn't have `-` in them, and if anything the word `go` should be dropped to make it just `dotenv`.

**Comment by coolaj86** [comment]
I'm highly in favor of `dotenv`.

**Comment by joho** [comment]
I won't be renaming this package as it's a language specific port of the initial ruby implementation named `dotenv` (out of both respect to the original and also I used to have a local fork of the ruby library and it clased)

I also lived throug the great Logrus rename and it was such a high effort low reward shitshow on the client side I wouldn't do it to anyone else without an incredibly strong reasons.

**Comment by dexterp** [comment]
I understand your reasons behind the decision as its a massive breaking change.

For me personally as I mainly use the binary with `make` it make sense to decouple the name from Go as I think its more conducive for adoption if the name wasn't prefixed with `go`.·

Consider if certain tools were prefixed with the original language `terraform` versus `goterraform`, it doesn't make it any less useful but if I was a pure Python programmer or pure Ruby (I use both), I would scratch my head and think is it just for Go programmers only?

I also have a slightly selfish motivation. I'm writing a [templating tool ](https://github.com/kick-project/kick) for project initialisation. When I get to it I want to include a `dotenv/godotenv` binary to a standard template that includes a `Makefile`. E.G.
```makefile
# Makefile
DOTENV := godotenv -f $(HOME)/.env,.env

.PHONY: _build

# Run "make build" will run this target prefixed with $DOTENV·
_build:
    gcc ...

# When "^${target}:" is called this catchall will look for an equvalent "^_${target}:" in the Makefile and execute it.
%:
    @egrep -q '^_$@:' Makefile && $(DOTENV) $(MAKE) _$@
```

My thoughts turn to how to promote adoption and hence my thought process.

`Godotenv` can definetly still be added to `homebrew` or an RPM/DEB created using goreleaser. Its the best compiled dotenv tool I've seen.
