### ISSUE TITLE
Thoughts on publishing binaries to Github Releases?

### ISSUE THREAD

**Issue by coolaj86** [joho/godotenv#116]
# Update: Published

Since I didn't hear anything back, I used the library to create my own command line binary and published:

- Github Releases: [github.com/therootcompany/dotenv/releases](https://github.com/therootcompany/dotenv/releases)
- Webi: [webinstall.dev/dotenv](https://webinstall.dev/dotenv)

**Mac**, **Linux**:

```bash
curl -sS https://webinstall.dev/dotenv | bash
```

**Windows 10**:

```bash
curl -A MS https://webinstall.dev/dotenv | powershell
```

I'm also flirting with the idea of using dotenv-rs for a smaller binary, but it's just so much easier to do automated cross-platform builds in Go.

## Original Question

I've been a fan of godotenv for a while and I'd like to add it to [webinstall.dev](https://webinstall.dev). Would you be willing to publish builds for this (i.e. Mac, Linux, Windows, x64, arm64) to Github Releases?

If you are, and you think that this is likely to have new versions in the future, I'd be happy to work with you on getting that to be an automated process.

+1 if the compiled binary could be called `dotenv` as was suggested in https://github.com/joho/godotenv/issues/113.

**Comment by dexterp** [comment]
Hello,

+1 for this feature

I also use godotenv in my go projects but I also want to use it in my non-go projects.

For example in my Makefile i use godotenv so that tasks load the .env file from my $HOME directory and from the project directory.

Running `make build` will ensure that the environment variables are available to all cli.
```
# Makefile
DOTENV := godotenv -f $(HOME)/.env,.env

build:
    $(DOTENV) make _build

_build:
    gcc .......

```

**Comment by coolaj86** [comment]
@joho Any feedback?

Also, I've recently discovered GoReleaser, which is incredibly easy to use. I've got a cheat sheet for it up at <https://webinstall.dev/goreleaser>. It takes about 5 minutes to go from `goreleaser init` to having the first published builds on Github, and just seconds each time after that.

**Comment by joho** [comment]
Yep, I'm happy to do this. I want to port CI into github actions anyway so will do it at the same time.

The binary isn't really the main point of this library (I never use it that way) but if y'all have the desire why not.

**Comment by joho** [comment]
Oh I read-read the update, it's done already, thanks. I'll still probably do it.

**Comment by dexterp** [comment]
@coolaj86, 
Side point on `goreleaser`. I was using it but the tool is "tightly coupled" to the full release process and it doesn't support `CGO`.

It would have been nice if it could generate RPM `.spec` files, and DEB source packages. It would have been easier to add projects to Fedora or Debian, Ubuntu.

As it stands it just creates a binary which would not be accepted upstream.

**Comment by coolaj86** [comment]
@dexterp 

> goreleaser ... doesn't support CGO.

Oh, but it does. I use it with CGO myself, see my cheat sheet at https://webinstall.dev/goreleaser

**Comment by dexterp** [comment]
@coolaj86 

From the documentation.
>  Unfortunately, GoReleaser does not support CGO.  Fortunately, there are ways to make it working. Checkout one of them

https://goreleaser.com/limitations/cgo/

I get you can actually make it work, but I've already got to many rabbit holes in other areas to go down to worry about it.
I just want the tool to work.

**Comment by coolaj86** [comment]
@dexterp That page of the docs is out of date. It's fully supported, no issues or rabbit holes. Looks like this:

```yml
- builds:
    - id: unarr-linux-aarch64
      main: ./cmd/unarr/unarr.go
      env:
        - CGO_ENABLED=1
        - CC=aarch64-linux-musl-gcc
      flags:
        - '-ldflags'
        - '-extldflags "-static"'
      goos:
        - linux
      goarch:
        - arm64
```

See [webinstall.dev/goreleaser](https://webinstall.dev/goreleaser) more explanation and a more complete example with many different targets.

Basic stuff like sqlite complies without any fuss. Even if your C code requires a lot of fuss to set up, you probably copy the same fuss over into the YAML file.

**Comment by joho** [comment]
Looks like something went wrong in PR tagging. #125 resolved this issue (but I've not yet published a new release with the binaries attached)

**Comment by joho** [comment]
Argh. github actions changed how they work between releases https://github.com/joho/godotenv/actions/runs/4021007738

> thatisuday/go-cross-build@v1.0.2 and svenstaro/upload-release-action@v2 are not allowed to be used in joho/godotenv. Actions in this workflow must be: within a repository owned by joho or created by GitHub.

**Comment by joho** [comment]
...and fixed, though one of the actions i'm relying on is deprecated.
