### ISSUE TITLE
Library can't parse multiline values properly

### ISSUE THREAD

**Issue by x1unix** [joho/godotenv#117]
Library doesn't parse multi-line variable values properly.

**Input**:

```bash
URLS="foo
bar"
```

**Expected:**

```go
map[string]string{
  "URLS": "foo\nbar",
}
```

**Got:**

```go
map[string]string{
  "URLS": "foo",
  "bar",
}
```

**Comment by x1unix** [comment]
@joho I'm already working on fix, but this requires a major rewrite of parser implementation

**Comment by x1unix** [comment]
@joho added PR with issue fix - https://github.com/joho/godotenv/pull/118.

Please take a look

**Comment by joho** [comment]
Duplicate of #64
