### ISSUE TITLE
Incorrect relative path to env in module

### ISSUE THREAD

**Issue by Spuxy** [joho/godotenv#129]
Hello was facing with an issue where i made custom package to use this library where .env is in my root project eg. "github.com/xy/hello" so my env was in github.com/xy/hello/.env and the custom pkg was in github.com/xy/hello/customPkg and in this pkg when i was trying to load env file i had to use 

`	err := godotenv.Load("../../.env")
	if err != nil {
		panic("no file has been found")
	}
	r := os.Getenv("TEST")
`

even when it should be ../.env

**Comment by burizz** [comment]
@Spuxy I am guessing you are getting this with "go run" of your package. This will probably show you why it doesn't find the file  - https://stackoverflow.com/questions/17014329/why-is-tmp-go-build644681611-command-line-arguments-obj-exe-passed-in-to-go-ru

In summary "**go run**" will compile your source into the system TEMP or TMP environment variable, then execute the file from there. If you check your /tmp dir you will see a bunch of previous builds that were created when you executed go run : 

```console
ls -la /tmp | grep -v app                                                                                                                                                                        root@DESKTOP-NG0SFLN
total 420
drwxrwxrwt 70 root root 135168 Jan 16 20:51 .
drwxr-xr-x 19 root root   4096 Jan 16 14:18 ..
drwx------  2 root root   4096 Dec 28 20:46 go-build007064825
drwx------  2 root root   4096 Jan 16 20:36 go-build013650962
drwx------  2 root root   4096 Dec 28 15:30 go-build025027116
drwx------  2 root root   4096 Dec 28 20:37 go-build032179725
drwx------  3 root root   4096 Jan 12 21:08 go-build039355260
drwx------  2 root root   4096 Jan  5 15:31 go-build040094670
drwx------  2 root root   4096 Jan 10 18:01 go-build044044658
drwx------  2 root root   4096 Jan 12 09:42 go-build061811458
drwx------  2 root root   4096 Jan 10 18:08 go-build067435242
drwx------  2 root root   4096 Dec 28 15:30 go-build075761735
drwx------  2 root root   4096 Jan 13 19:52 go-build076455347
drwx------  2 root root   4096 Jan 12 21:34 go-build093559270
drwx------  2 root root   4096 Dec 28 15:29 go-build139647395
```

One way it worked for me was to build the project Root path  : 
```go
package config

import (
	"path/filepath"
	"runtime"
)

var (
	// Get current file full path from runtime
	_, b, _, _ = runtime.Caller(0)

	// Root folder of this project
	ProjectRootPath = filepath.Join(filepath.Dir(b), "../")
)
```

Then pass your project root with the .env path : 

```go
godotenv.Load(config.ProjectRootPath + "/.env")
```

**Comment by joho** [comment]
Duplicate/related to #126
