### ISSUE TITLE
Generated env files do not end with newline character

### ISSUE THREAD

**Issue by gnarlex** [joho/godotenv#132]
The .env files generated by `godotenv` don't end with a newline character as expected.

Text files that don't terminate with a newline character can cause problems for some Unix tools and also doesn't conform with Unix standard (see [this stackoverflow answer](https://stackoverflow.com/a/729795/8800714)).

I will create a PR with a proposed fix for this.

**Comment by statik** [comment]
I think this issue could be closed now.
