### ISSUE TITLE
Proposal: add an "import" statement to the .env syntax

### ISSUE THREAD

**Issue by ansel1** [joho/godotenv#14]
Problem: My projects usually have a stack of .env files, all of which are optional.  For example, most of my projects have a .env, and allow an option .env.local, which overrides .env.  And when I run tests, the tests load .env.local, then .env.test, then .env.

It would be nice to run the godotenv command with a single file argument, like when running tests: `godotenv -f .env.test go test ./...`, while still loading the other .env files in the right precedence order.

Proposal:

If a .env file contains a comment line like:

```
# import: .env.local
```

When encountered, godotenv would essentially `Load()` that other file.  File not found errors would be ignored.  (a "must-import" directive could be added to require the presence of the other file).

So .env files could put "overrides" up top, and "defaults" at the bottom.  For example, the .env.local use case could be handled with a .env file like:

```
# load local developer overrides
# import: .env.local
key1=val
key2=val
```

The .env.test case could be handed by defining a .env.test file like:

```
# load local developer overrides
# import: .env.local
testkey1=value
# load defaults
# import: .env
```

Or, if a project wanted to have separate local overrides for both the default .env file and the .env.test file, the .env.test file could be:

```
# load local developer overrides
# import: .env.test.local
testkey1=value
# load defaults (which in turn loads .env.local overrides)
# import: .env
```

Issues: files could be loaded more than once.  This shouldn't pose an issue.  Circular references could occur, but could be detected by the loading code and error out.

**Comment by ansel1** [comment]
while looking at the implementation, it was easier to have imports override earlier variable declarations.  In other words, in the proposal, if all the imports are flatten out, I proposed that the earliest declaration of a variable wins, and later declarations would be ignored.  This matched godotenv's behavior with respect to existing environment variables, and the semantics of the Load() function.

But it's easier to implement the opposite: the last declaration wins.  And looking at it, this mirrors the normal semantics of sh scripts: if I source a bunch of shell scripts, later variable definitions override earlier ones.

I'm now wondering if I need a special "# import:" syntax for this, or if I could just make the parser recognize the normal sh syntax for importing another file: `. .env.local` or `source .env.local`.  That would maintain godotenv's effort to make .env files sourceable shell scripts, which will behave the same way if you source them.

**Comment by joho** [comment]
I have a strong preference for maintaining bidirectional compatibility with https://github.com/bkeepers/dotenv which doesn't support including/sourcing within files. I think there's more value in having consistent tooling for pretend ENV vars in dev between different languages in your environment than there is in growing the API surface of this library.

Thoughts?

**Comment by ansel1** [comment]
The thing is, there isn't bidirectional compatibility today, since godotenv doesn't support things like implicitly loading .env.local, the .env.{environment} conventions (which are very rails specific), and the command expansion stuff.  Plus, looking at dotenv packages in other languages, many of them have differences in what they support.  The node package, for example, has support multi-line support.

I'm mainly interested in bringing the .env.local and .env.{environment} stuff over to godotenv, since these seem to be pretty useful.  I keep trying to re-arrange my go projects around *not* having them, and keep finding the hoops to jump through more complex and inelegant that simply having them.  Actually, I could probably ditch .env.test without too much fuss, but the .env.local thing is pretty useful.

So I had a couple options: 

1. take another crack at implicitly loading .env.local.  I had another pull request outstanding for this, but it wasn't acceptable because it subtlety broke with the semantics of the Load() function.  Plus, it's somewhat "magical": it's done behind the curtains, and it's unclear what happens when you explicitly load a file not named ".env".  If I load "myvars", should dotenv implicitly load "myvars.local"?  Support for environment-specific overrides like bkeepers/dotenv has is even more magical, and coupled to rails.
2. Add a directive to the .env syntax which makes composition of .env files explicit, and allows godotenv users to write .env files behave the same with ruby dotenv, including the .local and .{env} support.  Ruby dotenv will ignore the `# import:` lines, but will do it's magic thing to load the stack of `.env` files.  The import directive gives additional flexibility to do stuff ruby's dotenv can't, but at least other dotenv impls won't choke on `# import:`.

This discussion does make me lean toward `# import:` instead of `source`.  .env files try to be compatible with both dotenv *and* bash, but it seems dotenv interop trumps bash interop.

**Comment by johanlunds** [comment]
I would prefer https://github.com/joho/godotenv/issues/10 over this one. We have .env.local in a Ruby project of ours.

**Comment by kukicado** [comment]
Has there been any progress or discussion on this? #12 seems to have been closed but not merged without any further comments or discussion.

**Comment by ansel1** [comment]
No.  There seemed to be pretty strong opposition to this idea.  There were a couple motivations for this which might have other solutions:

1. Support an implicit .env.local
2. Support optional files: if I run `godotenv -f .env.local,.env` and .env.local doesn't exist, .env is never read.  But I often want to write make targets or scripts which load a stack of .env files (overlaid on top of each other) which may or may not be there.  The command line doesn't support this, so you end up with `godotenv -f .env.local godotenv -f .env`.  That's not terrible for scripts, but not great for typing at the command line.

At the command line, having to pass really any arguments to godotenv defeats the convenience of using a dotenv tool in the first place.  How about this:

If the folder contains a .godotenv file, read options from that, including options which configure what files to load, in what order, and whether those files are optional or not.  And/or just make the command line tool always treat files as optional, i.e. if the file isn't there, skip it and try to load the next one.

**Comment by joho** [comment]
Yeah, as @ansel1 said I'm strongly opposed to syntax additions, I want to support env file portability between the range of different implementations.

Also as @ansel1 pointed out even earlier we don't currently have full compatibility with what the rails dotenv implementation offers. I'm all for supporting an implicit `.env.local` as it's how the upstream implementation handles it.

**Comment by kukicado** [comment]
Makes sense. Thanks for the additional information!
