### ISSUE TITLE
godotenv.Read(f) throws "unexpected character "<" in variable"

### ISSUE THREAD

**Issue by decentral1se** [joho/godotenv#150]
`godotenv.Read(filePath)` throws the following:

`FATA[0000] env file for 'foo.bar' couldn't be read: unexpected character "<" in variable name near "hosted by <a href=\"https://example.com\">Example.com</a>"`

The line in the `.env` file is:

`FOOTER="<a href="https://foo.org/">foobar</a> hosted by <a href="https://example.com">Example.com</a>"`

Seems like perhaps another variant of https://github.com/joho/godotenv/pull/58?

**Comment by decentral1se** [comment]
Or in other words, `godotenv` doesn't support HTML being passed via env var?

**Comment by tcharts-boop** [comment]
@decentral1se Hey, I wasn't able to reproduce this issue. I ran the following:

main.go:
```
package main

import (
	"fmt"
	"log"

	"github.com/joho/godotenv"
)

func main() {

	envMap, err := godotenv.Read("./.env")
	if err != nil {
		log.Fatal(err)
	}

	for k, v := range envMap {
		fmt.Printf("Key: %s, Value: %s\n", k, v)
	}
}

// OUTPUT: Key: FOOTER, Value: "<a href="https://foo.org/">foobar</a> hosted by <a href="https://example.com">Example.com</a>.
```

.env:
```
FOOTER="<a href="https://foo.org/">foobar</a> hosted by <a href="https://example.com">Example.com</a>.
```

go.mod:
```
module example.com/godotenv-test

go 1.16

require github.com/joho/godotenv v1.3.0
```

Could you post your full env file (with any secrets taken out)? What version of godotenv are you using?

**Comment by decentral1se** [comment]
Hey we ended up wrapping with `'` instead of `"` and it worked :see_no_evil: Sorry for the noise!
