### ISSUE TITLE
.dotenv does not work in go test

### ISSUE THREAD

**Issue by eugbyte** [joho/godotenv#154]
```
err := godotenv.Load()
	if err != nil {
		log.Fatalf("Error loading .env file: %v", err)
	}
```

No error is produced when running in development. However, when testing, e.g. go test, I get the error
```
Error loading .env file: open .env: The system cannot find the file specified.
```

Looks like during go test, the root directory is no longer respected

**Comment by joho** [comment]
duplicate of #126
