### ISSUE TITLE
I'm a... collaborator? How can I help?

### ISSUE THREAD

**Issue by coolaj86** [joho/godotenv#158]
Apparently I'm a collaborator on this repo, which is great. I'm more than happy to help.

However, I don't recall when this happened (and I can't find an email with the invite), and I'm not sure how to most appropriately use my powers for good.

Give me some guidance and boundaries and I'll see what I can do. :)

**Comment by scottwarren** [comment]
You get that label automatically in Github when you commit to the repository:
![image](https://user-images.githubusercontent.com/2718494/145783157-9f6e23f0-2ee2-4c17-b781-04fbf3b5d3f9.png)

**Comment by mholt** [comment]
Oh hey @coolaj86 -- are you still willing to maintain this? :smile:  

(I think GitHub uses "contributor" when you contribute to a repo, and "collaborator" when you're granted permissions to the repo. Confusingly similar.)

Would be nice to hear from @joho -- as we're looking at using this lib, possibly.

**Comment by coolaj86** [comment]
@mholt Yes, but it looks like @joho has gotten in all of the important fixes I was waiting for. Are there still outstanding issues that you need fixed?
