### ISSUE TITLE
Support for long lived applications

### ISSUE THREAD

**Issue by HeathNaylor** [joho/godotenv#16]
I am looking to have the .env file read more as a stream. Basically I just want the environment variables to update on the fly as I modify the .env file. This would allow for zero-downtime when modifying .env variables. My application is intended to run as a daemon on a system, never shutting down unless asked to.

**Comment by joho** [comment]
Unless I'm misunderstanding your request I don't think this is a good idea. In my experience convention is to only trigger a reload/refresh of configuration when your daemon receives a signal like `SIGHUP`. As go is call by value, unless you were making the `os.Getenv` call every time you needed a configuration value, you're highly likely to be passing around stale data.
