### ISSUE TITLE
Not parse yml lists

### ISSUE THREAD

**Issue by enydrueda** [joho/godotenv#19]
Hello, testing the format .env yml the code created not read that particular variable .

INTERFACES :
- eth0
- eth2

**Comment by joho** [comment]
Hi @enydrueda,

I just checked upstream in https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/parser.rb as to what the "offical" dotenv format supports, and it's best described as yaml-like, not true yaml.

So unfortunately there's no support for yaml arrays now or in the foreseeable future.
