### ISSUE TITLE
`-` is not supported in the key from version 1.5 but is supported in 1.4. Can we please take a look here ? This is a very basic use case.

### ISSUE THREAD

**Issue by raghavharness** [joho/godotenv#209]
**.env file content:**
`go-version=hello`

**Error while reading this file:**
unexpected character "-" in variable name near "go-version=hello\n"

The same works with 1.4 version.
@joho Request you to take a look into this.

**Comment by joho** [comment]
Thanks for raising.

While this could count as a regression against past versions, I'm counting this as undefined behaviour, and won't be fixing it.

I've gone and tested against the upstream ruby library and that format isn't supported there.

<img width="203" alt="image" src="https://user-images.githubusercontent.com/4092/227094212-9c105871-1a20-4126-bfb9-870db78b05f4.png">

It even syntax highlights funny in vim which is a reasonable leading indicator that usage is NQR.

**Comment by bradrydzewski** [comment]
@joho I wanted to provide some additional context. Although bash does not support dashes in environment variables, they are supported by the posix system call, and they are supported by windows. GitHub Actions supports environment files [1] and they allow dashes as well, and we are using this library to parse the GitHub Actions env files.

We completely understand they may be out of scope for this library, especially if you are tracking compatibility with the ruby version. We are going to keep an internal fork to patch the behavior, but if you ever change your mind, we would be happy to contribute back.

[1] https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
