### ISSUE TITLE
How tu use godotenv when testing implemented?

### ISSUE THREAD

**Issue by jutionck** [joho/godotenv#215]
=== RUN   TestProductRepositoryTestSuite
=== RUN   TestProductRepositoryTestSuite/TestPagingProduct_Success
2023/08/22 09:51:17 Error loading .env fileopen $PWD/test.env: no such file or directory

**Comment by BrianIto** [comment]
Duplicated of #126

**Comment by jutionck** [comment]
Okay thanks Brian
