### ISSUE TITLE
There was a problem using the command "go install github.com/joho/godotenv/cmd/godotenv@latest"

### ISSUE THREAD

**Issue by yuri-ynex** [joho/godotenv#220]
Hi, I'm having trouble with the following command, please tell me how to fix it, thank you very much!
apple@MacBook-Pro-2 rss-aggregator % go version
go version go1.20.12 darwin/amd64
apple@MacBook-Pro-2 rss-aggregator % go install github.com/joho/godotenv/cmd/godotenv@latest
go: github.com/joho/godotenv/cmd/godotenv@latest: module github.com/joho/godotenv/cmd/godotenv: Get "https://proxy.golang.org/github.com/joho/godotenv/cmd/godotenv/@v/list": dial tcp 172.217.25.17:443: i/o timeout

**Comment by joho** [comment]
This looks like a network issue either
* at your end
* on google's proxy
* on github

I can't help with any of the above sorry
