### ISSUE TITLE
New semver release tag

### ISSUE THREAD

**Issue by robvdl** [joho/godotenv#23]
Seems like the last release tag was v1, there have been a few years worth of commits since, it would be nice if a newer release tag could be created (semver style) thanks. It makes vendoring a lot easier.

**Comment by joho** [comment]
Done, via https://github.com/joho/godotenv/releases/tag/v1.1

Sorry, when I'd originally written this glide et al didn't have much uptake and so I didn't build any habits to stay on top of this.
