### ISSUE TITLE
Empty env var are not allowed anymore

### ISSUE THREAD

**Issue by goenning** [joho/godotenv#26]
Before PR #25 it was possible to have empty variables like 

```
MYVAR=somevalue
MYOTHERVAR=
```

As of current version I'm receiving a panic with `panic: runtime error: slice bounds out of range`. Is this by design? I like to leave empty variables as placeholders and to let others know which variables can be used.

I can send the PR if necessary.

Thanks!

**Comment by joho** [comment]
I think at this stage _either_ implementation is an accident on my part. I generally like to ensure the `.env` files are cross language compatible (ie could drop into a rails or php app) so let me check upstream for whether they're supported or not and we'll do whatever that is.

**Comment by joho** [comment]
Just tested a `.env` against the rubygem
```sh
FOO=BAR
BAZ=
BUM=POO
```
and got `"FOO"=>"BAR", "BAZ"=>"", "BUM"=>"POO"`

I also checked https://github.com/bkeepers/dotenv/blob/master/spec/dotenv/parser_spec.rb and it appears this is unspecified behaviour.

I'm happy to take a PR bringing support back, and then I might see if I can get that behaviour specified upstream.
