### ISSUE TITLE
if env var is set to an empty value in the environment, godotenv will overwrite it

### ISSUE THREAD

**Issue by ansel1** [joho/godotenv#28]
let's say I have an empty environment, and a `.env` file containing:

    COLOR=blue

then:

    $ godotenv env
    COLOR=blue

Now I set COLOR to an empty value:

    $ COLOR= godotenv env
    COLOR=blue

I don't think it should override my setting.  I tested with the ruby `dotenv`, it respects the env var being set, even to an empty value:

    $ COLOR= dotenv env
    COLOR=

**Comment by joho** [comment]
Right. Definitely a bug. I'll fix it.

**Comment by joho** [comment]
@ansel1 I've just pushed a branch with a fix - but as I feel like I've been on whack-a-mole break/fix around empty env vars I'd appreciate if you can pull down the branch and give it a secondary QA check.

**Comment by ansel1** [comment]
Tried it out.  The fix seems to work fine.  Thanks!

**Comment by joho** [comment]
Fixed in #29
