### ISSUE TITLE
Please Provide Annotated Release Tags

### ISSUE THREAD

**Issue by MTecknology** [joho/godotenv#30]
This package is used by Gitea which is a package I'm currently working to get into Debian. This means I get to do a review of all build dependencies. While working through your project, I saw that tags are used to mark releases, but they are not being annotated.

Unannotated release tags end up causing some headaches for packaging systems that monitor upstream activity--mostly for new releases--because the information is missing from 'git describe'. To annotate a tag, it just needs the -a flag passed. (git tag -a).

If you're willing to, it's possible to update the current tags (or just latest) with annotation. I've included some links [1] [2] that explain the process.

If you choose not to update tags, it would still be hugely appreciated if you could use annotated tags in the future.

[1] http://sartak.org/2011/01/replace-a-lightweight-git-tag-with-an-annotated-tag.html
[2] http://stackoverflow.com/questions/5002555/can-a-lightweight-tag-be-converted-to-an-annotated-tag

**Comment by joho** [comment]
Yep, more than happy to. My versioning strategy to date was add a tag once because someone asked once 😄 . Given the momentum behind the dep project I think I'll adopt semver, and add annotations as part of changing (ie actually having) a versioning plan.

**Comment by MTecknology** [comment]
Excellent, thanks!

**Comment by joho** [comment]
BTW I've gone and replaced the existing tags with annotated one already.

**Comment by MTecknology** [comment]
Thanks very much for doing that!
This is on it's way to being closed: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=859069
.. which in turn means this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792101

(for the record, that's become a generic stub at the bottom of many and isn't meant to be rude)
