### ISSUE TITLE
.env file output

### ISSUE THREAD

**Issue by alexquick** [joho/godotenv#31]
Hi, I've got a use case where it would be beneficial to be able to output `.env` files as well as read them. Is that something you'd be interested in a PR for or is it out of scope for this project?

**Comment by joho** [comment]
HI @alexquick my first instinct is that it would be out of scope. I don't want to dismiss it out of hand though. Maybe if you could elaborate on the usecase it would be an easier call one way or the other.

**Comment by alexquick** [comment]
Sure! I'm contributing to an [application](https://github.com/dokku/dokku) that manages the environments of other applications. As part of that it spends a fair degree of time working with dotenv files representing the environments of those applications, which it needs to both read and write.

Having one golang library to be able to roundtrip dotenv files would be nice. But on the other hand I understand that it's a pretty fringe use case.

**Comment by joho** [comment]
Let's give it a whirl. If it proves problematic it can always be extracted later.

**Comment by joho** [comment]
Fixed in #35
