### ISSUE TITLE
Load real env vars in production and use a .env locally

### ISSUE THREAD

**Issue by PierBover** [joho/godotenv#40]
This is pretty common in Node. You load a `.env` locally to simulate env vars, but when deploying to production or dev server (Heroku, AWS, etc) env vars are real and are only available to the person that configured the server.

It's dangerous to store critical data in the repo such as database users, password hashes, etc.

**Comment by joho** [comment]
I'm not quite sure what the issue you're reporting is. What you've described is what this library is for.

From the readme

**Comment by PierBover** [comment]
Maybe I'm missing something, but this example code in the README will fail when there is no .env file:

```
err := godotenv.Load()
  if err != nil {
    log.Fatal("Error loading .env file")
  }
```

But in a server environment like Heroku env vars are not loaded using an `.env` file. Usually each developer has its own `.env` file for local configuration and it's not committed to the repo.

Does autoload fail when a `.env` file is not found?

`import _ "github.com/joho/godotenv/autoload"`

What happens when env vars are already injected and a `.env` file is found?

**Comment by joho** [comment]
You've got a range of options:

* importing `autoload` ignores all errors
* you can ignore the error returned from `godotenv.Load()` - your linter may complain but it's valid go to do so
* (my preference) wrap the entire call to `Load` in an `if os.Getenv("APP_ENV") != "production"` so no one can sideload in an env file in your production box without also overriding existing env

**Comment by PierBover** [comment]
Thanks. I agree the third option is the best.

In node you can just import the `.env` from the command line so your actual code is completely pure.

Like this `node -r dotenv/config index.js`.
