### ISSUE TITLE
Quotes dropped at the end of a value

### ISSUE THREAD

**Issue by tobischo** [joho/godotenv#45]
When having a value which includes quotes, godotenv seems to drop them automatically:
```
TEST = "echo 'asd'"
```
results in
```
echo 'asd
```
Short term solution by adding a space after it works for our usecase, however I doubt that this is the case in general
example that works:

```
TEST = "echo 'asd' "
```
results in
```
echo 'asd'
```

In hindsight after reading
> The parser itself is pretty stupidly naive and I wouldn’t be surprised if it breaks with edge cases.

it is not particularly surprising.
Maybe this can be used as an example to make it a bit smarter?

**Comment by joho** [comment]
Thanks for the report, I'll fix that up.

**Comment by joho** [comment]
I've added a test case in #46 to match your report but the tests are passing. I know we made some parser fixes a while back - could you please confirm for me what release/commit you're on at your end?

**Comment by tobischo** [comment]
Well, this is embarassing.
Yes, you are absolutely right, it is already fixed and I should have updated the dependency and checked again before opening an issue.
My version was 3ddb2792f3923947290c4932990136e17852a078.
Sorry for the inconvenience 😞

**Comment by joho** [comment]
No problem, glad it's resolved.
