### ISSUE TITLE
Do support opting out for 'value quoteing" 

### ISSUE THREAD

**Issue by EugenMayer** [joho/godotenv#50]
Right now, when you open a file with godotenv and manipulate it, write it back, the values are all quoted.

In fact, that does not work out, since e.g. docker-compose does not allow those values to be quoted. So e.g.

That will work
```
COMPOSE_FILE=docker-compose.yml:docker-compose-dwcm.yml
```

while

```
COMPOSE_FILE="docker-compose.yml:docker-compose-dwcm.yml"
```

errors with 
`ERROR: .IOError: [Errno 2] No such file or directory: u'./"docker-compose.yml'`

Any way to opt out of "quoting" values? Thanks!

**Comment by EugenMayer** [comment]
I guess its all about that. 

If you see value in that, i can provide a PR for offering a third parameter to `Write` "skip_qoutes" and pass it down to Marshall.

Yet, i am not sure that is not "always" broken with quotes. Is it?

**Comment by joho** [comment]
I don't think there's a problem with always quoting the values (but happy to be shown to be wrong).

I just did a test with my local docker setup (with names changed to nonsense). `foo.yml` exists, `bar.yml` doesn't.

```
$> COMPOSE_FILE="buildkite.compose.yml" docker-compose up
Creating network "project_default" with the default driver
Pulling project (99designs/fake-project:latest)...
^CGracefully stopping... (press Ctrl+C again to force)
$> COMPOSE_FILE="foo.yml:bar.yml" docker-compose up
ERROR: .IOError: [Errno 2] No such file or directory: u'./bar.yml'
```

So I think you might just be missing one of the files.

**Comment by EugenMayer** [comment]
@joho that was rather a fact, not a suggestion :)

a) removing the quotes fixes it ( without obv. changing the path or filename ).

```
$~/test% ls -la
total 16
drwxr-xr-x    4 em  staff   136 Feb 12 10:23 .
drwxr-xr-x+ 129 em  staff  4386 Feb 12 10:23 ..
-rw-r--r--    1 em  staff    34 Feb 12 10:22 .env
-rw-r--r--    1 em  staff    85 Feb 12 10:22 docker-compose.yml

$~/test% docker-compose up
ERROR: .IOError: [Errno 2] No such file or directory: u'./"docker-compose.yml"'

$:~/test% cat .env
COMPOSE_FILE="docker-compose.yml"
```

while

```bash
$:~/test% cat .env
COMPOSE_FILE=docker-compose.yml

$:~/test% docker-compose up
Creating network "test_default" with the default driver
Pulling test (alpine:latest)...
^CGracefully stopping... (press Ctrl+C again to force)
```

**Comment by EugenMayer** [comment]
Also see https://github.com/docker/compose/issues/3702

**Comment by joho** [comment]
Ah, yep, Sorry. It was unclear to me from your first report and in the meantime I found https://docs.docker.com/compose/env-file/ too. It seems to me like the docker implementation is broken, while there's no real spec for `.env` files the convention is well established by the upstream ruby dotenv implementation.

I don't think I want to take on the extra API surface area to work around a bug in docker sorry.

**Comment by joho** [comment]
https://github.com/moby/moby/issues/12997 I think has a more detailed discussion of the docker/moby issue of `.env` compatibility

**Comment by EugenMayer** [comment]
@joho yeah, i understand you POV here - that seems to be an issue on the dc side rather. I implemented my own write method now, so i am not really in trouble - and as you mentioned, making this a usual accessible feature seems to not really make sense - point given. Thanks for the discussio
