### ISSUE TITLE
Variable substitution using real environment variable fallbacks

### ISSUE THREAD

**Issue by nick-jones** [joho/godotenv#74]
https://github.com/joho/godotenv/pull/54 introduced a change that meant substitution of variables from the real environment (i.e. not that derived from `.env` itself) was possible.

It looks like https://github.com/joho/godotenv/pull/58 removed this behaviour, in particular the deletion of `os.LookupEnv` - https://github.com/joho/godotenv/pull/58/files#diff-224f281bd0a4cfe0e7dcb394e8c7a585L299. Unfortunately it isn't clear from the PR if that was intended. Any chance someone can clarify?

**Comment by andrewmclagan** [comment]
Also needing this functionality back..

**Comment by fabriciojs** [comment]
@nick-jones @andrewmclagan well 1 year later, I had the same need in my project. 

I created https://github.com/joho/godotenv/issues/102.

For now I am using https://github.com/fireworkweb/godotenv (my fork) where I returned the behaviour.

Just registering this here in case some stumbles upon this issue and then can check the latest on this.

**Comment by nick-jones** [comment]
@fabriciojs :+1: there is also #72 and #88. Unfortunately no word from @joho on this.

**Comment by evandam** [comment]
Hey @fabriciojs we're looking for similar functionality, but where it is able to read environment variables from `os.Getenv` if the variable in the file has not been defined, like https://github.com/fireproofsocks/dotenvy/blob/main/docs/dotenv-file-format.md#interpolation-aka-variable-substitution.

Is this something that you would be able to update in your fork? (or @joho) 

Thanks!

**Comment by luisdavim** [comment]
#135 also relates to this.

**Comment by Envek** [comment]
Also made https://github.com/joho/godotenv/pull/227 as all other pull requests got stale due to parser rewrite in version 1.5.

**Comment by silverwind** [comment]
Is there a fork of this module with the feature added back? According to https://github.com/joho/godotenv/issues/182, the autor sees the module as "complete", I'm not sure on their stance regarding this issue.

**Comment by Envek** [comment]
But also according to #182:

> Exceptions will be made to:
> - …
> - maintain compatibility with env file formats of other mainstream "dotenv" libraries, primarily the **OG [Ruby dotenv](https://github.com/bkeepers/dotenv)** and the [Node.js dotenv](https://github.com/motdotla/dotenv)

And OG Ruby dotenv **[has](https://github.com/bkeepers/dotenv/blob/c9ecfa4e5598593dbadcf6c610cf5d8a9ed0bec1/spec/dotenv/parser_spec.rb#L66-L69)** variable substitution using real environment variables, so we can hope that @joho will finally notice #227 one day.

**Comment by silverwind** [comment]
> But also according to #182:
> 
> > Exceptions will be made to:
> > 
> > * …
> > * maintain compatibility with env file formats of other mainstream "dotenv" libraries, primarily the **OG [Ruby dotenv](https://github.com/bkeepers/dotenv)** and the [Node.js dotenv](https://github.com/motdotla/dotenv)
> 
> And OG Ruby dotenv **[has](https://github.com/bkeepers/dotenv/blob/c9ecfa4e5598593dbadcf6c610cf5d8a9ed0bec1/spec/dotenv/parser_spec.rb#L66-L69)** variable substitution using real environment variables, so we can hope that @joho will finally notice #227 one day.

Yes, expansion from environment also is a feature in JS `dotenv`, specifically with the `dotenv-expand` module that enables expansion:

https://github.com/motdotla/dotenv-expand/blob/ff7e2efd0d9925c7da82c167ae77d22a6c76e878/tests/main.js#L50-L64

**Comment by joho** [comment]
I'll give #227 a review and merge if I'm confident on backwards compatibility

**Comment by joho** [comment]
I've done a pre-release at https://github.com/joho/godotenv/releases/tag/v1.6.0-pre.1

I've set something in my calendar to do the full release on nov 15th (AU time) to give time for bug reports to come in and remediate if needed.

**Comment by silverwind** [comment]
pre.1 works fine for me, haven't noticed any regressions so far.
