### ISSUE TITLE
Specify path to .env

### ISSUE THREAD

**Issue by audreylim** [joho/godotenv#9]
Nice work here. I have my .env in the directory `website/`. I run go install from `src/` like this

```
go install github.com/audrey/website
```

How do I run this without having .env in the root directory ie. `src/` but in `website/`?

**Comment by joho** [comment]
Instead of using the autoimport option you can call `godotenv.Load("/foo/bar/website/.env")` as per http://godoc.org/github.com/joho/godotenv#Load which I _think_ fits your use case?

**Comment by audreylim** [comment]
Yes it does. Sorry I missed on this on your docs.
