### ISSUE TITLE
why only upper case variable substitution

### ISSUE THREAD

**Issue by FrankReh** [joho/godotenv#91]
Commit 992ab0ec added a regexp for variable substitution but the pattern only matches digits and upper case letters. Why not lower case letters too? (I see earlier code only supported upper case too.)

I added a-z to the pattern and it made the package work on my env variables and did not break any of the unit tests. Turns out all the unit tests are for upper case variables so far. The go package doesn't have problems with lower case or mixed case variables, nor does bash.

If this is intentional, perhaps a comment in the README stating only upper case are supported for canonical reasons or something like that.

Should go without saying but just in case ... nice package. Thanks for making it available to the go community!

**Comment by fgimian** [comment]
> 

Just encountered this too and am a bit confused by the current behaviour.

**Comment by FrankReh** [comment]
Anyway, no reason to keep an issue open this long.
