### ISSUE TITLE
Can .env files specify sourcing another .env file  in a way that can be used from both the shell and the package load function?

### ISSUE THREAD

**Issue by mojochao** [joho/godotenv#96]
In my dotenv files I'm trying to keep things DRY by sourcing other dotenv files.  This works great when I wish to apply a configuration to my shell environment, but it seems godotenv doesn't handle such usage.

Is there any way to accomplish usage from both the shell and godotenv load function?

**Comment by orxobo** [comment]
You really shouldn't mess up your dev environment with random environment variables, just keep all your environment variables in a file that godotenv loads `godotenv.Load("config.env")` when debugging and that you load into your docker/podman instance when testing.
You can add your environment variables file to your Makefile with:
` -include config.env`
then add them to your docker run command in your Makefile with:
`-e 'MY_APP_VARIABLE=${MY_ENV_VAR}' \`

Matt
