### ISSUE TITLE
Escaping the # character

### ISSUE THREAD

**Issue by JJBordy** [joho/godotenv#97]
If I have for example a variable in the .env file:
`Password=good#password`
The library will only read `good`
I tried escaping the `#` with one or more `/` symbols, doesn't work. Couldn't find a way to make it work.

**Comment by orxobo** [comment]
Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit.

http://www.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html

You may want to review your use of character #97 in environment variables.
Regards,
Matt

**Comment by JJBordy** [comment]
Hey, sorry. Yep.
I found that it works also if I put the variable value in quotes.
Great library ;)
